/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/jebena.glb 
*/

import { useGLTF, useTexture } from "@react-three/drei";
import React from "react";

export function Model(props) {
	const { nodes, materials } = useGLTF("/jebena.glb");
	const goldenTexture = useTexture({
		map: "./textures/golden/MetalGoldPaint002_COL_2K_METALNESS.png",
		normalMap: "./textures/golden/MetalGoldPaint002_NRM_2K_METALNESS.png",
		roughnessMap:
			"./textures/golden/MetalGoldPaint002_ROUGHNESS_2K_METALNESS.png",
		aoMap: "./textures/golden/MetalGoldPaint002_METALNESS_2K_METALNESS.png",
	});
	const metalicTexture = useTexture({
		map: "./textures/metalic/Metal_006_basecolor.jpg",
		normalMap: "./textures/metalic/Metal_006_normal.jpg",
		roughnessMap: "./textures/metalic/Metal_006_roughness.jpg",
		aoMap: "./textures/metalic/Metal_006_ambientOcclusion.jpg",
	});
	return (
		<group {...props}>
			<mesh
				geometry={nodes.j_chair.geometry}
				material={materials.chair_material}
				position={[0, 0.035, 0]}
				rotation={[Math.PI, -1.521, Math.PI]}
				scale={0.605}
			>
				<meshStandardMaterial {...metalicTexture} />
			</mesh>
			<mesh
				geometry={nodes.j_kdan.geometry}
				material={materials.kdan_material}
				position={[-0.563, 3.335, -0.006]}
				rotation={[1.702, -1.206, 1.712]}
				scale={0.207}
			>
				<meshStandardMaterial {...metalicTexture} />
			</mesh>
			<mesh
				geometry={nodes.jebena.geometry}
				material={materials.jebena_material}
				position={[-0.989, 1.353, -0.005]}
				rotation={[1.583, -0.239, 1.622]}
				scale={-0.131}
			>
				<meshStandardMaterial {...metalicTexture} />
			</mesh>
		</group>
	);
}

useGLTF.preload("/jebena.glb");
